# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ed87ef0661f6802bc8533a93f43b02e5"
name = "avada-onboarding-spfy"
handle = "avada-onboarding-spfy"
application_url = "https://foam-europe-standard-priced.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-c1e09ed3.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://foam-europe-standard-priced.trycloudflare.com/auth/callback",
  "https://foam-europe-standard-priced.trycloudflare.com/auth/shopify/callback",
  "https://foam-europe-standard-priced.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
